apiVersion: apps/v1
kind: Deployment
metadata:
  name: oksd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oksd
  template:
    metadata:
      labels:
        app: oksd
    spec:
      containers:
      - image: okteto.dev/oksd:latest
        name: oksd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "6a7611d6-6844-4d84-a293-64a53787ffc6"
        - name: Vless_Path
          value: "/vl55dsu5"
        - name: Vmess_UUID
          value: "6a7611d6-6844-4d84-a293-64a53787ffc6"
        - name: Vmess_Path
          value: "/vm66gs6"
        - name: Share_Path
          value: "/v2link"
